== 3.0.1

 Fix error when an entity un-targets another entity
 Fix falling block handling in protected areas
 Fix source-target filtering
 Improve movement handling logic for players and entities

== 3.0.0

This version introduces a new area file format based on Mojang's NBT format (.dat files).

You have to manually recreate all areas since there is no automatic file conversion from the old format to the new .dat format.

=== Additions

 Added 1.21.3 support

 Added area grouping (/area group)
 Added area inheritance (/area parent)
 Added area memberships (/area members)
 Added area ownerships (/area owner)
 Added area protections (/area protect)

 Added failed interaction messages
 Added proper WorldEdit restrictions
 Added support for more region types (Ellispoid, Cylinder)

=== News

 Area files are now backed up (.dat_old files)

=== API

 Added area creator api
 Added area inheritance
 Added grouped areas and regions
 Added more events
 Added persistent area data storage

 Improved error handling

 Switched from jetbrains annotations to JSpecify

 Use entities instead of players in ProtectionService

=== Internal changes

 Switched to brigadier
 Dropped json in favor of named binary tags
 Dropped jetbrains annotations in favor or JSpecify